FY-89/feat(core): add createElement and Fragment functions
42ForYou/RFS pull request #3
Opened 2024-01-22 17:11 UTC by daekuelee

- Implemented createElement function in core/createElement.js
- Added Fragment function to support JSX fragments
- Created test cases for createElement and Fragment in tests/core/createElement.test.js

close #FY-89

## Overview

[FY-](https://idealflower.atlassian.net/ blahblah)

## PR Checklist

-   [ ] I read and included theses actions below

1. I have written documents and tests, if needed.

2024-01-22 17:43 UTC, daekuelee commented
test error

2024-01-23 03:58 UTC, JinMuGo requested changes
아래 내용을 확인하셔서 수정 바랍니다!

2024-01-23 03:58 UTC, JinMuGo commented on srcs/core/createElement.js
> +        return isArray(val) ? acc.concat(flatten(val)) : acc.concat(val);
isArray를 isArr로 변경해서 import하고 있는데, 이부분만 타이핑 수정해주시면 될 것 같습니다.

2024-01-23 06:06 UTC, JinMuGo approved these changes
수정 사항 확인하였습니다!

2024-01-23 06:09 UTC, merged